---
title: "STAT 1200 Linear Regression III Examples"
format: pdf
editor: visual
---

```{r}
library(car)
library(MASS)
data("SLID") #1993

SLID$sexIND <- ifelse(SLID$sex == "Female", 1, 0)
```

# Example 1 from slides

```{r}

data("Cars93")

lmA <- lm(Price~Horsepower + Man.trans.avail, data = Cars93)
summary(lmA)


```

# Example 2 from slides

```{r}


lmB <- lm(Price ~ Horsepower + relevel(DriveTrain, "Rear"), data = Cars93)
summary(lmB)



levels(SLID$language)
```

```{r}

set.seed(1200)
library(ggplot2)

X1 = rnorm(77,1,1)
Y = X1 + runif(77,1,2)
X2 = factor(rbinom(77,1,0.5))

df1 <- data.frame(Y, X1 , X2 )

ggplot(data = df1, mapping = aes(y = Y, x = X1, color = X2))+
         geom_point() +
         geom_smooth(method = "lm")+
  labs(title = "No effect of Second Independent Variable")




X1 = rnorm(77,1,1)
X2 = factor(rbinom(77,1,0.5))
Y = X1 + runif(77,1,2) + 5*as.numeric(X2)



df2 <- data.frame(Y, X1 , X2 )

ggplot(data = df2, mapping = aes(y = Y, x = X1, color = X2))+
         geom_point() +
         geom_smooth(method = "lm")+
  labs(title = "Effect of Second Independent Variable but No Interaction")





X1 = rnorm(77,1,1)
X2 = factor(rbinom(77,1,0.5))
Y = X1 + runif(77,1,2) + X1*as.numeric(X2)



df3 <- data.frame(Y, X1 , X2 )

ggplot(data = df3, mapping = aes(y = Y, x = X1, color = X2))+
         geom_point() +
         geom_smooth(method = "lm")+
  labs(title = "Effect of Second Independent Variable and Interaction")




```

# Example 3 from slides

```{r}

# No Effect and No Interaction

lmC <- lm(Y~ X1 + X2 + X1:X2, data = df1)
summary(lmC)

#No Interaction

lmD <- lm(Y~ X1 + X2 + X1:X2, data = df2)
summary(lmD)


# Interaction

lmE <- lm(Y~ X1 + X2 + X1*X2, data = df3)
summary(lmE)
```

# Example 4 from slides

```{r}

lm4.1 <- lm(Price~Horsepower, data = Cars93)
lm4.2 <- lm(Price~Horsepower + Man.trans.avail, data = Cars93)
lm4.3 <- lm(Price~Horsepower + Man.trans.avail + Horsepower:Man.trans.avail, data = Cars93)

anova(lm4.1,lm4.2) # Not better, choose smaller
anova(lm4.1,lm4.3) # Not better, choose smaller

AIC(lm4.1) # Smaller
AIC(lm4.2)

BIC(lm4.1) # Smaller
BIC(lm4.2)

# lm4.1 is the best of these three


data("diamonds")

```
